### ISSUE TITLE
Monitoring the ignition battery.

### ISSUE THREAD

**Issue by ola-aberg** [bionicbone/Gasser_Monitor_v1#70]
Will it be possible to monitor the battery for ignition? 
A slightly more difficult task to solve because you need to avoid getting interference from the ignition system to the receiver.

**Comment by bionicbone** [comment]
Not sure I follow, are you saying you have a separate battery for ignition and another for servo control?

DI'd you see this page?
https://github.com/bionicbone/Gasser_Monitor_v1/wiki/08.Charging-Gasser-Fight-Battery

**Comment by ola-aberg** [comment]
Yes.
Most gasoline engines have a battery-powered electronic ignition system.
You cannot use the same battery for ignition, receivers and servos.
If you do, you get severe interference from the ignition system that can knock out the receiver.

You use one battery for the ignition system and another battery for the receiver and servos.

The part of the sensor that monitors the ignition battery must be galvanically separated from the receiver in the same way as an optocoupled switch, a so-called kills switch, which is used to switch the ignition on and off to the engine.

I have read the wiki and have not found any sensor that can monitor the battery of the ignition system.

It is not possible to monitor both the ignition system battery and the "flight battery" on the same circuit without problems with interference from the ignition system.

/ Ola

**Comment by bionicbone** [comment]
Thanks for explaining, I see what you are getting at and confirm currently this project does not do what you want.
